server:
  port: 9093
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-seriralizer: org.apache.kafka.common.serialization.StringSerializer
      value-seriralizer: org.apache.kafka.common.serialization.StringSerializer
